name = "astro_ssr"
main = "./dist/_worker.js"
compatibility_date = "2023-06-15"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "astro_db"
database_id = "a244c38a-6786-493b-a7ed-cde70181d53c4"